//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace santisartapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLASS_copy1
    {
        public int CLASS_ID { get; set; }
        public string STATUS { get; set; }
        public string CLASS_NAME_ID { get; set; }
        public Nullable<int> TEACHER_ID { get; set; }
        public Nullable<int> CLASS_ROOM { get; set; }
        public Nullable<int> CLASS_YEAR_INDEX { get; set; }
    }
}
