//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace santisartapp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPONENT
    {
        public int COMPONENT_ID { get; set; }
        public string COMPONENT_TYPE { get; set; }
        public string COMPONENT_VALUE { get; set; }
        public string COMPONENT_NAME { get; set; }
        public string COMPONENT_DES { get; set; }
    }
}
