    //------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace santisartapp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class testEntities : DbContext
    {
        public testEntities()
            : base("name=testEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<rt> rt { get; set; }
        public DbSet<tblUsers> tblUsers { get; set; }
        public DbSet<CLASS> CLASS { get; set; }
        public DbSet<CLASS_copy1> CLASS_copy1 { get; set; }
        public DbSet<COMPONENT> COMPONENT { get; set; }
        public DbSet<ENROLL_PAID> ENROLL_PAID { get; set; }
        public DbSet<ENROLL_PAY> ENROLL_PAY { get; set; }
        public DbSet<ENROLL_STUDENT_CLASS> ENROLL_STUDENT_CLASS { get; set; }
        public DbSet<FOOD> FOOD { get; set; }
        public DbSet<MONTHLY> MONTHLY { get; set; }
        public DbSet<STUDENTS> STUDENTS { get; set; }
        public DbSet<ddddd> ddddd { get; set; }
    }
}
